### ISSUE TITLE
What about adding sitemap generation part?

### ISSUE THREAD

**Issue by svetlyak40wt** [egao1980/cl-sitemaps#1]
I'm working on a clack middleware which will serve `sitemap.xml` file, and already made a code which serializes cl-sitemaps' structures back to XML. If you would like, I'll contribute to the library and bring a few `make-*` functions plus a `render-sitemap` function.

What do you think?

**Comment by egao1980** [comment]
Fixed by https://github.com/egao1980/cl-sitemaps/pull/2
